spring:
  profiles:
    active: test-rabbitmq-postgresql
---
spring:
  config:
    activate:
      on-profile: test-rabbitmq-postgresql
  datasource:
    url: jdbc:postgresql://localhost:15432/testadmin
    username: testadmin
    password: 1111

    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
---
spring:
  config:
    activate:
      on-profile: testmysql
  datasource:
    url: jdbc:mariadb://localhost:39907/codingtest
    username: root
    password: 1111

    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
